name: WolfPound
main: com.fernferret.wolfpound.WolfPound
author: FernFerret
version: 0.4
commands:
  adopt:
    description: Gives you a wolf! (You'll need to befriend it though...)
    usage: /<command>