name: WolfPound
main: com.fernferret.wolfpound.WolfPound
author: FernFerret
version: 1.0
commands:
  adopt:
    description: Gives you a wolf!
    usage: /<command>
  wpsetprice:
    description: Gives you a wolf!
    usage: /<command>
  wpsetaggro:
    description: Gives you a wolf!
    usage: /<command>
  wpsettype:
    description: Sets the type of currency used to buy a wolf. {Use i:ITEM_NAME|money|ITEM_ID}
    usage: /<command> [TYPE] {global|w:WORLD}
  wpremoveprice:
    description: Removes the price from the current world if none is specified, or all if global is specified
    usage: /<command> {global|w:WORLD}